name: jeevandhara
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  geoflutterfire_plus: ^0.0.33
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
#  firebase_app_check: ^0.3.0+3
  provider: ^6.1.2
  geolocator: ^11.1.0
  http: ^1.2.2
  url_launcher: ^6.3.1
  socket_io_client: ^2.0.3
  intl: ^0.19.0
  google_maps_flutter: ^2.5.0
  shazzy_map:
    path: packages/shazzy_map
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/jeevan_dhara_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
